version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: book_db
    ports:
      - "3306:3306"
    networks:
      - booknet

  book-app:
    image: book-project
    container_name: book-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test123
    depends_on:
      - mysql
    networks:
      - booknet

networks:
  booknet:
